services:
  mongoserver:
    image: mongo
    container_name: mongodb-server
    environment:
      - MONGO_INIDB_ROOT_USERNAME=chatappdb
      - MONGO_INIDB_ROOT_PASSWORD=chatappdb##3398
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - chatapp-network
  backendapi:
    image: skshoyebdev/chatappbackend:v2
    container_name: chatapp-backend-server'
    ports:
      - '5513:5513'
    networks:
      - chatapp-network
    env_file: .env
    depends_on:
      - mongoserver

networks:
  chaapp-network:
    driver: bridge